extern crate hyper;
extern crate reroute;

use std::fs::File;
use std::io::{BufReader, Result};
use std::io::prelude::*;

use hyper::Server;
use hyper::server::{Request, Response};
use reroute::{Captures, RouterBuilder};

fn not_found(req: Request, res: Response, _: Captures) {
    let uri = format!("{}", req.uri);
    let msg = format!("No service found behind '{}'.", uri);
    res.send(msg.as_bytes()).unwrap();
}

fn parse_capture(cap: &String) -> Vec<String> {
    let caps: Vec<&str> = cap.split(|c| c == ',' || c == '/').collect();
    let mut list: Vec<String> = Vec::new();
    // &caps[2..] is used to skip `/api/`
    for val in &caps[2..] {
        if val.is_empty() {
            continue;
        }
        list.push(val.to_string());
    }
    list
}

fn list_handler(_: Request, res: Response, c: Captures) {
    let cap = c.unwrap();
    let caps = parse_capture(&cap[0]);
    let mut re = "; Generated by editorconfig.me\n".to_string();

    for target in caps {
        let content = match read_file(&target) {
            Ok(c) => c,
            Err(e) => {
                println!("Could not process '{}'. {:?}", target, e);
                format!("; Could not process '{}'\n", target)
            }
        };
        re.push_str(&content);
    }
    res.send(re.as_bytes()).unwrap();
}

fn get_file_name(name: String) -> String {
    let mut full_name = "./files/".to_string();
    full_name.push_str(&name);
    full_name.push_str(".editorconfig");
    full_name
}

fn read_file(name: &String) -> Result<String> {
    // let mut full_name = "./files/".to_string();
    // full_name.push_str(&name);
    let file = File::open(name)?;
    let mut reader = BufReader::new(file);
    let mut contents = String::new();

    reader.read_to_string(&mut contents)?;

    Ok(contents)
}

fn main() {
    let mut builder = RouterBuilder::new();

    builder.get(r"/api/(,?(\w)+)+", list_handler);

    builder.not_found(not_found);

    let router = builder.finalize().unwrap();

    Server::http("127.0.0.1:3000")
        .unwrap()
        .handle(router)
        .unwrap();
}

#[test]
fn test_parse_capture() {
    let actual = parse_capture(&"/api/,rust,,markdown,".to_string());
    let expected = vec!["rust".to_string(), "markdown".to_string()];
    assert_eq!(actual, expected);
}

#[test]
fn test_read_file() {
    let actual = read_file(&"test/testfile".to_string()).unwrap();
    let expected = "testtesttest\n".to_string();
    assert_eq!(actual, expected);
}

#[test]
fn test_get_file_name() {
    let actual = get_file_name("rust".to_string());
    let expected = "./files/rust.editorconfig".to_string();
    assert_eq!(actual, expected);
}
